---
abstract: 'use C<Tickit> with C<POE>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::HexString: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Tickit
provides:
  POEx::Tickit:
    file: lib/POEx/Tickit.pm
    version: 0.02
requires:
  POE: 0
  Tickit: 0.32
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
